### ISSUE TITLE
Extra }); in Step 5 in main.js

### ISSUE THREAD

**Issue by twhetzel** [googlecodelabs/polymer-bluetooth#2]
In [Step 5](https://codelabs.developers.google.com/codelabs/polymer-bluetooth/index.html?index=..%2F..%2Fubiquity&viewga=UA-41980257-1#4)  the last }); in the screenshot for main.js doesn't match up.  Not a big deal, but a little harder to follow opening and closing brackets in Chrome Dev Editor.

**Comment by beaufortfrancois** [comment]
Thank you @twhetzel for the feedback.
I can't see the extra `});` in Step 5 ;(

**Comment by twhetzel** [comment]
Actually, to my eyes it looks like the snippet in main.js in Step 5 has 2 extra });  the two at the very end. When I review just this snippet, I don't see opening parenthesis to match. It's a little hard to see opening/closing parens in the Chrome Dev Editor vs. Sublime or Android Studio.

**Comment by beaufortfrancois** [comment]
I've removed them so that it's easier to read. It will hopefully be published today ;)
Thank you for the feedback!
